default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer

  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: go-build
      - id: go-mod-tidy

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.4
    hooks:
      - id: go-test-repo-mod
        stages: [push] # only run tests on push, not on commit
